name: CI with SaltStack API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ci_key
        chmod 600 ~/.ssh/ci_key
        ssh-keyscan -H 3.130.220.130 >> ~/.ssh/known_hosts

    - name: Add config file
      run: |
        cat ansible/koshee-ci-server/ssh_config > ~/.ssh/config
        chmod 600 ~/.ssh/config
        chmod 700 ~/.ssh
  
    - name: Transfer files to Salt Master
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete . "${{ secrets.SALT_MASTER_USER }}@${{ secrets.SALT_MASTER_HOST }}:/home/koshee/koshee/protect/salt"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Execute Salt commands via script
      run: |
        ./salt-api.sh
