name: CI with SaltStack API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: Transfer files to Salt Master
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete . "${{ secrets.SALT_MASTER_USER }}@${{ secrets.SALT_MASTER_HOST }}:/home/koshee/koshee/protect/salt"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Execute Salt commands via script
      run: |
        ./salt-api.sh
