name: CI with SaltStack API

on:
  push:
    branches:
      - feature/salt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ci_key
        chmod 600 ~/.ssh/ci_key
        ssh-keyscan -H ${{ secrets.SALT_MASTER_HOST }} >> ~/.ssh/known_hosts

    - name: Add config file
      run: |
        cat salt/ssh_config > ~/.ssh/config
        chmod 600 ~/.ssh/config
        chmod 700 ~/.ssh
  
    - name: Transfer files to Salt Master
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete --exclude=.git --filter=':- .gitignore' . "${{ secrets.SALT_MASTER_USER }}@${{ secrets.SALT_MASTER_HOST }}:/home/koshee/koshee/protect/salt_test"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Execute Salt commands via script
      env:
        SALT_MASTER_HOST: ${{ secrets.SALT_MASTER_HOST }}
        SALT_MASTER_USER: ${{ secrets.SALT_MASTER_USER }}
        SALT_MASTER_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        ./salt/salt-api.sh

    - name: Execute Salt commands via ssh
      env:
        SALT_MASTER_HOST: ${{ secrets.SALT_MASTER_HOST }}
        SALT_MASTER_USER: ${{ secrets.SALT_MASTER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ./salt/salt-ssh.sh
    
