name: CI with SaltStack API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: Transfer files to Salt Master
      run: |
        sshpass -p koshee rsync -avz --delete . "koshee@3.130.220.130:/home/koshee/koshee/protect/salt_new"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Execute Salt commands via script
      run: |
        ./salt-api.sh