name: Workflow PR Test

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TARGET: 'CoreCluster6'

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    concurrency:
      group: ci
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install ssh agent
      run: sudo apt-get install -y libpam-ssh-agent-auth
  
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ci_key
        chmod 600 ~/.ssh/ci_key
        ssh-keyscan -H 3.130.220.130 >> ~/.ssh/known_hosts

    - name: Add config file
      run: |
        cat salt/ssh_config > ~/.ssh/config
        chmod 600 ~/.ssh/config
        chmod 700 ~/.ssh
  
    - name: Execute test-nvidia-smi
      run: |
        sudo systemctl restart sshd
        ssh-add ~/.ssh/ci_key
        ssh -A koshee-ci-server "sudo salt $TARGET state.apply states.tests.test-nvidia-smi"

    - name: Execute test-config-load
      run: |
        ssh -A koshee-ci-server "sudo salt $TARGET state.apply states.tests.test-config-load"
        
    - name: Execute test-evaluate-config
      run: |
        ssh -A koshee-ci-server "sudo salt $TARGET state.apply states.tests.test-evaluate-config"

    - name: Execute test-detect-build
      run: |
        ssh -A koshee-ci-server "sudo salt $TARGET state.apply states.tests.test-detect-build"
    
    - name: Execute test-config-from-env
      run: |
        ssh -A koshee-ci-server "sudo salt $TARGET state.apply states.tests.test-config-from-env"
